arenas:
  0:
    world: "world"
    locations:
      1:
        x: -0
        y: 65
        z: -26
      2:
        x: -0
        y: 65
        z: -19
economy-rewards: true
duel-rewards:
  # Reward format:
  # [ITEM] (item:amount) eg. [ITEM] diamond:1
  # [MONEY] amount eg. [MONEY] 100

messages:
  sent-request: "§eYou sent a duel request to [player] successfully." # Used
  refused-request: "§eYou refused [player]'s duel request successfully." # Used
  request-accepted: "§eYou accepted [player]'s duel request successfully." # Used
  request-received: "§eYou received a duel request from [player]." # Used
  player-request-accepted: "§e[player] accepted your duel request." # Used
  player-request-refused: "§c[player] refused your duel request." # Used
  player-null: "§cThat player is offline or doesn't exist!" # Used
  player-myself: "§cYou can't send a duel request to yourself!" # Used
  request-already-sent: "§cYou already sent a duel request to that player!" # Used
  no-duel-request: "§cYou don't have a duel request from that player!" # Used
  win-message: "§aCongratulations! §eYou won!" # Used
  lose-message: "§cOh no, you lost! §eBetter luck next time!" # Used
  teleport-message: "§eYou're getting teleported back to your location in 5 seconds..." # Used